add ContentParser
bashenjoyers/superbash pull request #12
Opened 2022-09-19 20:43 UTC by pogrebnoijak

2022-09-20 06:23 UTC, bagrorg requested changes

2022-09-20 06:23 UTC, bagrorg commented on src/main/kotlin/parsing/ContentParser.kt
> +    private fun splitSpace(input: String): List<String> {
Как насчет `splitBySpace`? Не сразу по названию понял, что имеется ввиду

2022-09-20 06:23 UTC, bagrorg commented on src/main/kotlin/parsing/ContentParser.kt
> +//        println(splitters)
Возможно, это стоит удалить

2022-09-20 06:23 UTC, bagrorg commented on src/main/kotlin/parsing/ContentParser.kt
> +        }
Возможно, стоит выделить это в отдельную функцию. Например, что-то вроде `tryCreateFirstEntity`?

2022-09-20 06:56 UTC, pogrebnoijak commented on src/main/kotlin/parsing/ContentParser.kt
> +        }
Я бы оставил так, надо подумать...

2022-09-23 22:36 UTC, mandelshtamd requested changes

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
>  class ContentParser {
Ты как-нибудь проверял, что он работает?

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +            TWO_MARK    // "
лучше quote_mark и single_mark, имхо

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +            STANDARD,
а standard чему соответствует?

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +        fun one() = when(state) {
Будет здорово, если название будет чуть более явно отражать что делает функция, по one тяжело понять зачем она нужна

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +        fun two() = when(state) {
аналогично с one

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +        splitters.drop(1).forEach { arg ->
а почему для first entity исключение ловим и обрабатываем, а для других нет?

2022-09-23 22:36 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +            '\'' -> {
кажется, лучше параметризовать енам значением, за которое он отвечает и тут использовать State.SINGLE_MARK и тд

2022-09-24 09:50 UTC, pogrebnoijak commented on src/main/kotlin/parsing/ContentParser.kt
>  class ContentParser {
Ну все части, что я написал работают, да (по крайней мере на чём-то базовом)

2022-09-24 09:51 UTC, pogrebnoijak commented on src/main/kotlin/parsing/ContentParser.kt
> +            STANDARD,
Состоянию вне кавычек, я не смог придумать название лучше и в readme оно же было.

2022-09-24 09:53 UTC, pogrebnoijak commented on src/main/kotlin/parsing/ContentParser.kt
> +        fun one() = when(state) {
Переназвал под State, но вообще как по мне только хуже стало, это достаточно внутренняя штука и тут нормально так писать

2022-09-24 09:54 UTC, pogrebnoijak commented on src/main/kotlin/parsing/ContentParser.kt
> +        splitters.drop(1).forEach { arg ->
Так работает сам алгоритм, мы пытаемся разобрать первое как keyword, если не удалось, то это Initialization. Штука, которая ловит всё где-то дальше

2022-09-25 17:34 UTC, bagrorg approved these changes
LGTM

2022-09-26 09:10 UTC, mandelshtamd commented on src/main/kotlin/parsing/ContentParser.kt
> +        fun one() = when(state) {
"это достаточно внутренняя штука и тут нормально так писать"
так мы стремимся писать так, чтобы понятно было, поэтому какая разница внутренняя или не внутренняя.
но осталось мало времени, так что ок, пусть будет как будет, главное чтобы ты помнил что за что отвечает

2022-09-26 09:11 UTC, mandelshtamd approved these changes

2022-09-26 18:54 UTC, merged