add CLIEntityCreator and KeywordCreator
bashenjoyers/superbash pull request #13
Opened 2022-09-19 20:43 UTC by pogrebnoijak

2022-09-20 08:50 UTC, mandelshtamd requested changes

2022-09-20 08:50 UTC, mandelshtamd commented on src/main/kotlin/parsing/CLIEntityCreator.kt
> +     * Создаёт [Initialization] по переданному *expression*
Давай комментарии на английском писать, а то комментарии в котором каждое второе слово на разных языках (initialization,expression) выглядит странно

2022-09-20 08:50 UTC, mandelshtamd commented on src/main/kotlin/parsing/CLIEntityCreator.kt
>  class CLIEntityCreator {
лучше еще написать комментарий к классу

2022-09-20 08:50 UTC, mandelshtamd commented on src/main/kotlin/parsing/KeywordCreator.kt
>  class KeywordCreator {
и тут тоже комментарий к классу лучше написать

2022-09-23 22:24 UTC, mandelshtamd requested changes

2022-09-23 22:24 UTC, mandelshtamd commented on src/main/kotlin/parsing/KeywordCreator.kt
> +    fun createKeyword(keyword: String, context: Context): Keyword = when(keyword) {
Мне кажется, context лучше в параметр конструктора вынести

2022-09-24 09:41 UTC, pogrebnoijak commented on src/main/kotlin/parsing/KeywordCreator.kt
> +    fun createKeyword(keyword: String, context: Context): Keyword = when(keyword) {
Он может поменяться или ты хочешь ещё добавить операции для его обновления в _KeywordCreator_?

2022-09-25 17:33 UTC, bagrorg approved these changes
LGTM

2022-09-25 17:33 UTC, bagrorg commented on src/main/kotlin/parsing/KeywordCreator.kt
> +    fun createKeyword(keyword: String, context: Context): Keyword = when(keyword) {
Лично мне он нравится больше как аргумент
Предлагаю не отклоняться от заданной документации

2022-09-25 17:33 UTC, bagrorg commented on src/main/kotlin/parsing/CLIEntityCreator.kt
> +    fun createInitialization(expression: String): Initialization = Initialization()
Несмотря на то что мы в фазе 1, у нас все равно есть функция `getVariable` и я бы предложил сохранять ее
Правда мне кажется, что скорее всего эта задача решится, когда будут реализовываться `executor`'ы

2022-09-26 09:08 UTC, mandelshtamd commented on src/main/kotlin/parsing/KeywordCreator.kt
> +    fun createKeyword(keyword: String, context: Context): Keyword = when(keyword) {
>"Он может поменяться"
Так мы ссылку передаем. Мы наверно просто апдейтить существующую мапу будем, а не создавать новую, поэтому на ссылку это не повлияет. Но ок, я не настаиваю, чтобы передавалось через конструктор

2022-09-26 09:08 UTC, mandelshtamd approved these changes

2022-09-26 18:54 UTC, merged