+ i/o console classes
bashenjoyers/superbash pull request #14
Opened 2022-09-20 06:32 UTC by bagrorg

2022-09-20 08:33 UTC, pogrebnoijak commented on src/main/kotlin/io/ConsoleContentInput.kt
> +    override fun getContent(): String {
мне кажется тут лучше `override fun getContent() = readln()` и в других аналогичным местах тоже

2022-09-20 08:34 UTC, pogrebnoijak commented on src/main/kotlin/io/ConsoleContentOutput.kt
> +    private fun printPrompt() {
тут наверно print

2022-09-20 08:47 UTC, mandelshtamd requested changes

2022-09-20 08:47 UTC, mandelshtamd commented on src/main/kotlin/io/ContentInput.kt
> +     * @return content as `String`
Было бы здорово договориться о едином формате комментариев, потому что сейчас где-то написано, что возвращается, а где-то нет.

Давай во всех комментариях указывать что принимается и что возвращается

2022-09-20 16:01 UTC, bagrorg commented on src/main/kotlin/io/ContentInput.kt
> +     * @return content as `String`
Что указывать, если ничего не принимается/возвращается?

2022-09-20 16:07 UTC, pogrebnoijak commented on src/main/kotlin/io/ContentInput.kt
> +     * @return content as `String`
ничего

2022-09-23 08:42 UTC, pogrebnoijak approved these changes

2022-09-23 08:42 UTC, pogrebnoijak commented on src/main/kotlin/io/ConsoleContentInput.kt
>  }
Тут без return же вроде

2022-09-23 22:19 UTC, mandelshtamd commented on src/main/kotlin/io/ConsoleContentInput.kt
>  }
+, лучше либо block body c return использовать, либо expression body без return

2022-09-23 22:20 UTC, mandelshtamd approved these changes

2022-09-25 17:29 UTC, merged